# Workflow for deploying Next.js static content to GitHub Pages
name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      # Copy content directory into site directory for build
      - name: Copy content directory
        run: |
          mkdir -p site/content
          cp -r content/* site/content/

      - name: Install dependencies
        working-directory: ./site
        run: pnpm install

      - name: Build site
        working-directory: ./site
        run: pnpm build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site/out'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
